"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const user_router_1 = __importDefault(require("./user.router"));
const util_router_1 = __importDefault(require("./util.router"));
const product_router_1 = __importDefault(require("./product.router"));
const customer_router_1 = __importDefault(require("./customer.router"));
const supplier_router_1 = __importDefault(require("./supplier.router"));
const estimation_router_1 = __importDefault(require("./estimation.router"));
const sale_router_1 = __importDefault(require("./sale.router"));
const return_router_1 = __importDefault(require("./return.router"));
const refund_router_1 = __importDefault(require("./refund.router"));
const damage_router_1 = __importDefault(require("./damage.router"));
const credit_note_router_1 = __importDefault(require("./credit-note.router"));
const purchase_router_1 = __importDefault(require("./purchase.router"));
const transaction_router_1 = __importDefault(require("./transaction.router"));
const search_router_1 = __importDefault(require("./search.router"));
const mainRouter = express_1.default.Router();
mainRouter.use("/users", user_router_1.default);
mainRouter.use("/utils", util_router_1.default);
mainRouter.use("/products", product_router_1.default);
mainRouter.use("/customers", customer_router_1.default);
mainRouter.use("/suppliers", supplier_router_1.default);
mainRouter.use("/estimations", estimation_router_1.default);
mainRouter.use("/sales", sale_router_1.default);
mainRouter.use("/returns", return_router_1.default);
mainRouter.use("/refunds", refund_router_1.default);
mainRouter.use("/damages", damage_router_1.default);
mainRouter.use("/credit-notes", credit_note_router_1.default);
mainRouter.use("/purchases", purchase_router_1.default);
mainRouter.use("/transactions", transaction_router_1.default);
mainRouter.use("/search", search_router_1.default);
exports.default = mainRouter;
