"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiError = void 0;
/**
 * Child of Error Class used for handling when there is an error generated by any module of api
 *
 * @extends Error
 */
class ApiError extends Error {
    /**
     * Constructor method for the ApiError class.
     * @param {string} type Error type
     * @param {string} message Error message details
     */
    constructor(type, message) {
        super(message);
        this.type = type;
    }
}
exports.ApiError = ApiError;
